[theme]
# Deep navy for a legal-professional accent
primaryColor = "#2E5090"

# Light gray for clean reading space
backgroundColor = "#F9F9F9"

# Subtle blue-gray sidebar, reminiscent of citation manuals
secondaryBackgroundColor = "#E6EBF2"

# High-contrast dark text
textColor = "#262730"

# san-Serif font for legal-style readability
font = "Arial"

[server]
# For local development, headless can be false
headless = true

# Allow CORS for API integrations if needed
enableCORS = false

# Auto-pick a port on Streamlit Cloud
port = 8501

# Allow larger file uploads for internal PDFs or .pkl files
maxUploadSize = 100

[browser]
# Optional browser settings
serverAddress = "localhost"
serverPort = 8501
gatherUsageStats = false

[deprecation]
# See warnings when using outdated Streamlit features
showWarningOnDirectExecution = true

[logger]
# Logging level (options: error, warning, info, debug)
level = "info"

[global]
# Helpful to remind users about unsaved work
showWarningOnClose = true

# Disable sharing session state across tabs for citation integrity
shareSessionState = false
